src/zip.c
mz_zip_reader_extract_to_file fails when you ask it to extract a directory (according to the comment on line 621 of miniz.h and confirmed by my tests), thus zip_extract will fail if it attempts to decompress a zip file if that zip file contains a directory (there is an exception but I will not go into it here). This patch corrects the issue.
=> zip_extract: handle directories within zip files

src/miniz.h
When enabling the clang adress-saniziser the function mz_zip_array_push_back used with a size of 0 bytes will be detected as a possible NULL-pointer-refererence-error and the test failes. My pull request will close this gap.
=> Fix possible NULL-Ptr detection from clang

src/zip.c
The 'rpl' pointer in the 'rpl ++' expression could be nullptr. In such
case, resulting value will be senseless and it should not be used.
Check lines: 94, 86.
=> Fix https://www.viva64.com/en/w/v769/

.gitignore, CMakeLists.txt
This PR replaces the CMake variables `CMAKE_PROJECT_NAME` and `CMAKE_SOURCE_DIR` with `PROJECT_NAME` and `PROJECT_SOURCE_DIR`. This allows `zip` to be nested in other CMake projects using `include_subdirectory()` with CMake 3.x without changing the behavior when using CMake 2.8. This change is needed because the behavior of the `CMAKE_PROJECT_NAME` and `CMAKE_SOURCE_DIR` variables changed with CMake 3.x.
For example, in CMake 2.8, the [documentation states that `CMAKE_PROJECT_NAME` is](https://cmake.org/cmake/help/v2.8.12/cmake.html#variable:CMAKE_PROJECT_NAME)
> The name of the current project. This specifies name of the current project from the closest inherited PROJECT command.
While in CMake 3.12, the [documentation states that `CMAKE_PROJECT_NAME` …
=> Use project-local CMake variables instead of top-level CMake variables

.gitignore, CMakeLists.txt
When incorporating zip as a subdirectory in a larger CMake-based project, dependent targets need to be told where to find the zip.h file. The simplest way to do that is with a target_include_directories() call in the CMakeLists.txt file.
=> Use target_include_directories to help dependents find the zip.h file

src/miniz.h
I got warning when tried to compile with `--std=c99`
```
$ gcc -std=c99 -c zip.c
In file included from zip.c:35:
miniz.h: In function ‘mz_zip_file_read_func’:
miniz.h:4137:20: warning: implicit declaration of function ‘ftello’; did you mean ‘ftell’? [-Wimplicit-function-declaration]
#define MZ_FTELL64 ftello
^~~~~~
miniz.h:4657:22: note: in expansion of macro ‘MZ_FTELL64’
mz_int64 cur_ofs = MZ_FTELL64(pZip->m_pState->m_pFile);
^~~~~~~~~~
miniz.h:4138:20: warning: implicit declaration of function ‘fseeko’; did you mean ‘fseek’? [-Wimplicit-function-declaration]
#define MZ_FSEEK64 fseeko
^~~~~~
miniz.h:4660:9: note: in expansion of macro ‘MZ_FSEEK64’
(MZ_FSEEK64(pZip->m_pState->m_pFile, (mz_int64)file_ofs, SEEK_SET))))
```
`man ftello` says that `ftello` feature support should be ckecked …
=> Add c99 support

src/zip.c
`zip_entry_close(0)` produces crash.
=> Fix crash in zip_entry_close

src/zip.c
See https://github.com/kuba--/zip/blob/master/src/zip.c#L322, here called `free` for `const char*`.
=> Fix cast from const warning

src/zip.h
The MXE build environment (to cross-compile Windows binaries from Linux) uses the _SSIZE_T_DEFINED instead of the _SSIZE_T, and fails otherwise due to conflicting types.
=> Fix ssize_t check for MXE

src/zip.c
Included the ability to extract symlinks, as this is needed in my use case. I did not include the ability to zip symlinks, as I did not need it.
If any changes are needed, I'm happy to make them.
=> added ability to extract zipped symlinks as symlinks on UNIX platform

src/zip.c
The function name `basename` is used in `"string.h"` in some Linux
environments, so rename it to `get_basename` to avoid naming conflicts
in those environments.
=> Rename basename to base_name.

src/miniz.h
As discussed in #92 : 
I removed the failing assertion, then the library runs smoothly on the tested hardware.
=> remove unecessary assertion in miniz.h (#92)

src/zip.c, test/test.c
Need to explicity set UNIX file permissions when commpressing buffer
to entry. Without it later unpacked file can't be opened.
Fix #100
=> Fix UNIX file permissions

CMakeLists.txt, cmake/Config.cmake.in, test/CMakeLists.txt
I want to add this package to the Hunter package manager: https://github.com/ruslo/hunter
To do so, we need to export the library target in the modern CMake fashion. No Hunter-specific changes need to be made since the library has no dependencies.
This line
`install(FILES ${PROJECT_SOURCE_DIR}/src/zip.h DESTINATION ${INCLUDE_INSTALL_DIR}/zip)`
means that library consumers need to include
`#include <zip/zip.h>`
which avoids conflicts with other libraries that may use the same filename (`zip.h`).
=> Update CMake files with Config install and some cleanup

.gitignore, src/miniz.h, src/zip.c, test/test_miniz.c
Add support for 64 bit fields in central directory by
updating `..._central_dir` functions in `miniz.h` header from upstream library.
It closes: #107
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kuba--/zip/108)
=> Support for 64-bit fields

CMakeLists.txt, src/zip.c, src/zip.h, test/test.c
@kuba-- 
I have implemented the entry deletion function. The idea is to obtain the offset and data length of every file data in the ZIP file first, then move the data behind the deleted entry forward to overwrite the deleted data, and in the  end truncate the invalid data at the end of the ZIP file. The case of deleting one folder (multiple files) at a time is considered in the implementation.
=> Add delete entry function

src/zip.h
Support `ssize_t` for some _mingw32_ version
=> define __have_typedef_ssize_t

src/zip.c
When building with visual studio with `Preview - Features from the Latest C++ Working Draft (std:c++latest)` we get the following error
I hope it does not create issues for other windows compilers.
=> fix compilation error for msvs latest

src/miniz.h
There is a small typo in src/miniz.h.
Should read `purposely` rather than `purpsosely`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, purpsosely -> purposely

CMakeLists.txt
Add an option to build static zip without PIC. Default is still PIC.
=> Allow static lib without PIC

.github/workflows/build.yml, CMakeLists.txt, src/zip.h, test/CMakeLists.txt
It results in cleaner shared libs for non-msvc builds, and avoid to use CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS for Visual Studio (it was useless for MinGW by the way).
=> Exports symbols of API and hides others symbols

CMakeLists.txt
It is usually recommended to be explicit, to provide reproducible builds, instead of relying on the availability of a dependency on the build machine to decide if something should be build or not, or a feature added or not.
=> CMake: add ZIP_BUILD_DOCS option

CMakeLists.txt
to be consistent with zip::zip imported target in generated config file
=> CMake: add zip::zip ALIAS target

src/miniz.h
In miniz.h in the str2wstr function, the malloc result hasn't been casted to wchar_t* which results in a C2440 compiler error on MSVC :)
=> Fix MSVC C2440 pointer cast error

src/zip.c
Commas were missing in zip_errlist, which could cause unexpected behavior
=> Fix zip_errlist missing commas

src/miniz.h
Fixes https://github.com/kuba--/zip/issues/205
=> Fix - unsafe _wfopen and _wfreopen in Visual Studio

CMakeLists.txt
Only testcase in the project is supported by the sanitizer function, so add sanitizers for zip to facilitate bug detection.
=> Add sanitizers for zip

src/zip.c, test/test_read.c, test/test_write.c
Hello.
This pull request is a port of features from miniz that our company required for our usage of this library (many thanks for releasing it!). I think that they could be also useful to others, so here is a pull request for your consideration.
The code modified has been almost directly ported from this file:
https://github.com/richgel999/miniz/blob/master/miniz_zip.c
with minor changes to adapt the code to this project and simplify the port.
There are some points that I think that deserve to be commented:
a) This pull request makes the library to always create ZIP64 files
This has been forced with the flag `MZ_ZIP_FLAG_WRITE_ZIP64` and has being done this way because the interface of the library doesn't require to know the number of files to ZIP or their size in advance (so initially …
=> Port of features from miniz (creation of ZIP64 files and empty folders)

CMakeLists.txt, src/miniz.h, src/zip.c
I changed the cmake in my local repo, please help to check if the macro name is suitable , also I met one crash
in zip_entry_open for zip is nullptr because my wrong usage, so I changed the time pointer of check null pointer
=> for support shareable file open on windows

src/miniz.h, src/zip.c, test/test_append.c
Closes https://github.com/kuba--/zip/issues/217
=> No freopen for append

src/zip.c
Similar to lines https://github.com/kuba--/zip/blob/dce6952692c9bad22a951ac7ef0933a333f3933e/src/zip.c#L1182-L1184.
Fixes compiling with tcc on linux.
=> Wrap mz_zip_time_t_to_dos_time() call

src/miniz.h
As per comment in https://github.com/kuba--/zip/blob/a597bdf814684a5a8b4adbae8597f03c865601fd/src/miniz.h#L1250
Fix compiling with `-Werror=switch-enum`.
=> Add switch case for MZ_ZIP_TOTAL_ERRORS

src/zip.c
Compiling fails on some plattforms when jumping over variable initialisation => init them in a block
=> do not jump over initialisation

src/miniz.h, src/zip.c, src/zip.h
- Change comments to be ANSI C style
- Use MSVC-specific __int* types instead of stdint
- Replace unsigned long long type with a unsigned __int64 (introducing a zip_ull typedef)
- Remove calls to MS-specific functions that did not exist in MSVC 6.0:
- _wfopen_s -> _wfopen
- _wfreopen_s -> _wfreopen
- _wstat64 -> wstati64 (along with _stat64 struct)
- _ftelli64 -> ftell
- _fseeki64 -> fseek
- localtime_s -> localtime
- _chsize_s -> _chsize
- strcpy_s -> strcpy
- strncpy_s -> strncpy
- Use __inline attribute instead of inline
- Move variable definitions to the start of the blocks
=> Port to MSVC 6.0

CMakeLists.txt
I think it would be a good idea to add something like this in general (I know I need it), but not necessarily exactly like this.
Great project, BTW!
=> Enable building tests only if the project is built as a standalone one

src/zip.c
Fixes https://github.com/kuba--/zip/issues/272
=> strncpy filename_size

src/zip.c
The function `zip_open("somefile.zip", 0, 'r');` fails if `somefile.zip` is read-only.
To test this, just add a call to `chmod(ZIPNAME, S_IRUSR);` (needs `sys/stat.h` included) to the end of `test_setup()` in `test/test_read.c`.
The reason for this is that `'r'` uses this:
https://github.com/kuba--/zip/blob/114d9d46fdbdad55b37705190a8625f4ab5fa81a/src/zip.c#L847
..which in turn uses this:
https://github.com/kuba--/zip/blob/114d9d46fdbdad55b37705190a8625f4ab5fa81a/src/miniz.h#L5999
An `fopen()` with mode `r+` means that it's opened read-write.
This PR fixes it by using `mz_zip_reader_init_file_v2()` (which opens in `rb` mode, not `r+b` mode) when opening files in `'r'` mode.
This fix should help with the downstream issue https://github.com/SuperIlu/DOjS/issues/28
=> Allow opening read-only ZIP files

src/miniz.h
This fixes clang yelling about `*tdefl_compressor_alloc()` and `tinfl_decompressor_alloc()`
```
zip/src/miniz.h:4019:41: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
zip/src/miniz.h:4771:45: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
```
=> Fix clang build error on Windows

src/zip.c
Prevents an uninitialized warning when MINIZ_NO_TIME is defined. Follows zip_entry_close.
=> Initialize dos_time and dos_date in _zip_entry_open

src/miniz.h
I remember I created this pr 3 years ago, but recently I upgrade to 0.3.0 , and found on windows can not zip the opened files.
so I check the macro lost. just add them back.
=> for windows ZIP_ENABLE_SHARABLE_FILE_OPEN

src/zip.c
I also verified that the build and tests still work with this change.
=> Replace strcpy with more secure strncpy

src/zip.c
Had to add function that achieved the zip_move_files for an in memory buffer and change some of the internal functions to take objects that provided enough context information to operate on an in memory archive or disk-backed archive.
=> Fix to enable deletion of files in stream memory zips.

.github/workflows/build.yml, src/zip.c, src/zip.h, test/test_extract.c, test/test_open.c
Closes https://github.com/kuba--/zip/issues/337
=> Open archive from C stream (FILE *)

src/zip.c
Compiling the code with GCC14 this particular line triggers calloc-transposed-args since the size is provided as the first argument. The order of arguments for calloc is number and then size.
=> Fix incorrect order of argument to calloc

src/miniz.h, test/CMakeLists.txt, test/test_permissions.c
The version-made-by field was not set when creating an archive. When the archive is extracted by unzip in Linux and macOS, the origin file permissions (especially executable perms) are lost. 
This patch adds the missing field.
=> Fix permissions to work with unzip

README.md, src/zip.c, src/zip.h, test/test_read.c
The new function `zip_entry_noallocread_offset()` will allow us to stream content from a zip file.
I know there was no discussion beforehand, so consider this as a draft and discussion material.
=> Added zip_entry_noallocreadwithoffset
