.gitignore, .travis.yml, CMakeLists.txt, README.md, src/zip.c, src/zip.h, test/main.c
=> Add zip_entry_(f)read

README.md
Add Ring programming language example! (http://ring-lang.net)
=> Add example in the Ring programming language (RingZip)

src/miniz.h
https://github.com/kuba--/zip/issues/29
=> Expression 'pZip->m_pState' is always true.

src/zip.c
https://github.com/kuba--/zip/issues/30
=> Expression '!pFilename' is always false

README.md, src/zip.c, src/zip.h, test/test.c
Added:
```
zip_entry_size(zip);
zip_entry_crc32(zip);
```
=> Add more stats functions

src/zip.c
It fixes: https://github.com/kuba--/zip/issues/46
=> Fix MSYS2 MinGW 64

src/zip.c, test/test.c
Closes https://github.com/kuba--/zip/issues/50
=> Fix fopen_s return is error

src/miniz.h
=> Fix dereferencing type-punned pointer warnings

appveyor.yml, test/test.c
Fixes https://github.com/kuba--/zip/issues/59
@drizt - Please take a look if it works with MSYS2 on windows
=> chmod 666 to delete the test file on windows

src/zip.c
Closes https://github.com/kuba--/zip/issues/56
@drizt - could you check if it works or you?
=> Check __STDC_LIB_EXT1__

src/zip.c, src/zip.h, test/test.c
=> Make read functions syscall compatible.

CMakeLists.txt, test/CMakeLists.txt
test output for linux must be "*.out"
=> Change CmakeLists.txt

src/zip.h
Closes https://github.com/kuba--/zip/issues/110
=> Add __DEFINED_ssize_t for alpine gcc

src/zip.c, src/zip.h, test/test.c
It's partly related to https://github.com/kuba--/zip/issues/109
@maxsupermanhd - please take a look on this PR (if it works for you).
This is what I can quickly add to check if x64 headers exist.
=> Check if the archive has a zip64 end of central directory headers.

src/zip.c, src/zip.h, test/test.c
Fixes #126  . Part 1
zip_open_stream() I will do it later. 
@kuba-- 
But first Check whether zip_extract_stream() is appropriate.
=> zip_extract_stream()

src/zip.c
using real_filename() to fix issue #123
=> fix issue #123

src/zip.c, src/zip.h, test/test.c
@kuba-- 
I implemented zip_open_stream(), which supports decompression from memory to memory.
WDYT？
=> Add zip_open_stream()  func.

src/zip.c, test/test.c
...don't skip hidden (dot) files
Fixes https://github.com/kuba--/zip/issues/157
=> Fix normalize entry path

src/zip.c, test/test.c
Fixes https://github.com/kuba--/zip/issues/165
=> Fix return code for extract

README.md, src/zip.c, src/zip.h, test/test_append.c, test/test_entry.c
For public API ` s/zip_total_entries/zip_entries_total/`
=> Minor API changes

src/zip.c, src/zip.h, test/test_append.c, test/test_entry.c, test/test_extract.c, test/test_permissions.c, test/test_read.c, test/test_write.c
If it's possible try to return an error code instead of (always) -1 on error.
=> Return code on error

src/miniz.h
Fixes https://github.com/kuba--/zip/issues/164
=> Replace _wfopen_s by _wfopen, _wfreopen_s by _wfreopen

src/miniz.h, src/zip.c, test/test_permissions.c
+ use MZ_FOPEN where it's possible.
=> Custom mz_stat for MSC

src/miniz.h, src/zip.c
Closes https://github.com/kuba--/zip/issues/198
=> Fix compiler warnings on win

.github/workflows/build.yml, CMakeLists.txt, README.md, src/miniz.h, src/zip.c, src/zip.h, test/test_append.c, test/test_entry.c, test/test_extract.c, test/test_permissions.c, test/test_read.c, test/test_write.c
Closes: https://github.com/kuba--/zip/issues/144
=> Upgrade miniz to v2.2.0

CMakeLists.txt, src/zip.c
=> [CMakeLists.txt] Set C89; [src/zip.c] C89-compatibility

src/miniz.h, src/zip.c
...to mz_zip_writer_add_to_central_dir
=> pass MZ_ZIP_GENERAL_PURPOSE_BIT_FLAG_UTF8

.gitignore, src/miniz.h, src/zip.h
=> MAX_PATH=1024

src/zip.c
Fixes https://github.com/kuba--/zip/issues/234
=> Fix compilation on MS-DOS/DJGPP

src/zip.c
Probably fixes https://github.com/kuba--/zip/issues/243
=> replace S_IWRITE by S_IWUSR

src/miniz.h
New PR since https://github.com/kuba--/zip/pull/251 got lost.
=> fix mkdir for tcc on Windows

src/zip.c
New PR since https://github.com/kuba--/zip/pull/252 got lost.
=> fix ftruncate for tcc on Windows

src/miniz.h
Closes https://github.com/kuba--/zip/issues/258
=> Fix unzip big files

README.md
Currently the API is not complete, but it is easy to expand on in the future.
=> Include lua

src/zip.c, test/CMakeLists.txt, test/test_static.c
Fixes https://github.com/kuba--/zip/issues/342
=> Try to fix #123

CMakeLists.txt
otherwise compile failed on Android NDK r27
=> suppress implicit function declaration errors

src/miniz.h
See this similar PR for details: https://github.com/richgel999/miniz/pull/329
This is to help remedy CVE-2018-12913.
=> Patch miniz.h to guard against infinite loop bug
